services: # список контейнеров.
  app:
    build: . # собирать образ из Dockerfile в текущей папке.
    ports:
      - "8000:8000" # пробрасываем порт 8000 контейнера на порт 8000 хоста (чтобы обращаться к localhost:8000).
    environment: # передаём переменные окружения
      - ENV=development
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    volumes: # монтируем текущую папку проекта в /app внутри контейнера.
      - .:/app

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: taskflow_user
      POSTGRES_PASSWORD: taskflow_password
      POSTGRES_DB: taskflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: